version: "3.3"

services:
  app:
    build: ./containers/${WEBSERVER}
    environment:
      - LOG_LEVEL=${APP_LOG_LEVEL}
    volumes:
      - ../${PROJECT}:/var/www/html
      - ./logs/php:/var/log/php
      - ./logs/app:/log
    restart: always

  mysql:
    build: containers/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./data/mysql:/var/lib/mysql
      - ./data/backup:/backup
    restart: always

  nginx:
    build: ./containers/nginx
    ports:
      - 80:80
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./src/app:/var/www/html
    command: nginx -g "daemon off;"
    restart: always

